#!/usr/bin/env bash
# AuditEngine launcher — orchestrator.
# Entry point for ./dev and AuditEngine.command. macOS-only (uses `security`, `open`).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# shellcheck source=./keychain.sh
source "$SCRIPT_DIR/keychain.sh"

C_BLU=$'\033[1;34m'; C_CYN=$'\033[1;36m'; C_GRN=$'\033[1;32m'; C_YEL=$'\033[1;33m'; C_RED=$'\033[1;31m'; C_DIM=$'\033[2m'; C_RST=$'\033[0m'
step()  { printf "  ${C_CYN}[>]${C_RST} %s\n" "$1"; }
ok()    { printf "  ${C_GRN}[+]${C_RST} %s\n" "$1"; }
warn()  { printf "  ${C_YEL}[!]${C_RST} %s\n" "$1"; }
fail()  { printf "  ${C_RED}[x]${C_RST} %s\n" "$1"; exit 1; }

WITH_DOCKER=0
RESET_KEYCHAIN=0
NO_OPEN=0
for arg in "$@"; do
  case "$arg" in
    --with-docker)     WITH_DOCKER=1 ;;
    --reset-keychain)  RESET_KEYCHAIN=1 ;;
    --no-open)         NO_OPEN=1 ;;
    -h|--help)
      cat <<USAGE
AuditEngine local launcher

  ./dev                    Start Vite (5173) + Express API (3001), cloud Supabase
  ./dev --with-docker      Also bring up local Postgres + Redis + Ollama
  ./dev --reset-keychain   Re-prompt for all Keychain secrets
  ./dev --no-open          Do not open browser tabs

Stop:
  ./stop                   Graceful shutdown (also fires on Ctrl+C)
USAGE
      exit 0 ;;
  esac
done

# ── Banner ────────────────────────────────────────────────
printf "\n${C_BLU}══════════════════════════════════════════════════════════════${C_RST}\n"
printf "${C_BLU}  AuditEngine v10 — local dev launcher${C_RST}\n"
printf "${C_BLU}══════════════════════════════════════════════════════════════${C_RST}\n\n"

# ── Preflight ─────────────────────────────────────────────
step "Preflight checks"

[ "$(uname -s)" = "Darwin" ] || warn "Not macOS — Keychain features will fail; continue at your own risk"

command -v node >/dev/null 2>&1 || fail "node not found — install Node 20 (https://nodejs.org)"
node_major="$(node -v | sed -E 's/^v([0-9]+).*/\1/')"
if [ "$node_major" -lt 20 ]; then
  fail "Node $(node -v) is too old — need 20.x"
elif [ "$node_major" -gt 20 ]; then
  warn "Node $(node -v) is newer than tested (20.x); proceeding"
fi
ok "Node $(node -v)"

command -v npm >/dev/null 2>&1 || fail "npm not found"
ok "npm $(npm -v)"

[ -d "$REPO_ROOT/.git" ] || fail "Not a git repo — run from your Audit-Engine clone"
if [ -n "$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null)" ]; then
  warn "Working tree has uncommitted changes — launcher will continue anyway"
fi

disk_avail_kb="$(df -k "$REPO_ROOT" | awk 'NR==2 {print $4}')"
[ "$disk_avail_kb" -gt 512000 ] || fail "Less than 500 MB free on this volume — clear space first"
ok "Disk: $((disk_avail_kb / 1024)) MB free"

# ── Keychain ──────────────────────────────────────────────
if [ "$RESET_KEYCHAIN" = "1" ]; then
  step "Resetting Keychain entries (re-prompt)"
  for k in $(keychain_list_managed); do keychain_clear "$k"; done
  bash "$SCRIPT_DIR/setup-keychain.sh"
elif ! keychain_has VITE_SUPABASE_URL || ! keychain_has VITE_SUPABASE_ANON_KEY || ! keychain_has ANTHROPIC_API_KEY; then
  step "First launch — running Keychain setup wizard"
  bash "$SCRIPT_DIR/setup-keychain.sh"
else
  ok "Keychain entries found"
fi

# ── Materialise .env.local ────────────────────────────────
step "Materialising .env.local from Keychain (chmod 600)"
ENV_LOCAL="$REPO_ROOT/.env.local"
umask 077
cat > "$ENV_LOCAL" <<EOF
# Generated by scripts/launcher/launch.sh — do not edit by hand
# Regenerated every launch from macOS Keychain. Edits will be lost.
# Run \`./dev --reset-keychain\` to change values.

VITE_SUPABASE_URL=$(keychain_get VITE_SUPABASE_URL)
VITE_SUPABASE_ANON_KEY=$(keychain_get VITE_SUPABASE_ANON_KEY)
VITE_CLAUDE_API_KEY=$(keychain_get VITE_CLAUDE_API_KEY)
ANTHROPIC_API_KEY=$(keychain_get ANTHROPIC_API_KEY)
SUPABASE_SERVICE_KEY=$(keychain_get SUPABASE_SERVICE_KEY)
JWT_SECRET=$(keychain_get JWT_SECRET)
GITHUB_TOKEN=$(keychain_get GITHUB_TOKEN)
SENDGRID_API_KEY=$(keychain_get SENDGRID_API_KEY)
SLACK_BOT_TOKEN=$(keychain_get SLACK_BOT_TOKEN)
COMPANIES_HOUSE_API_KEY=$(keychain_get COMPANIES_HOUSE_API_KEY)

VITE_APP_ENV=development
VITE_APP_NAME=AuditEngine
VITE_APP_VERSION=10.0.0
VITE_APP_URL=http://localhost:5173
PORT=3001
NODE_ENV=development
CORS_ORIGIN=http://localhost:5173
EOF
chmod 600 "$ENV_LOCAL"
umask 022
ok ".env.local written ($(wc -l < "$ENV_LOCAL" | tr -d ' ') lines, 0600)"

# ── Install deps ──────────────────────────────────────────
if [ ! -d "$REPO_ROOT/node_modules" ] || [ "$REPO_ROOT/package-lock.json" -nt "$REPO_ROOT/node_modules/.package-lock.json" ]; then
  step "Installing dependencies (npm ci)"
  if [ -f "$REPO_ROOT/package-lock.json" ]; then
    npm ci --silent
  else
    npm install --silent
  fi
  ok "Dependencies installed"
else
  ok "Dependencies up to date"
fi

# ── Optional Docker stack ─────────────────────────────────
DOCKER_USED=0
if [ "$WITH_DOCKER" = "1" ] || [ "${AUDITENGINE_DOCKER:-0}" = "1" ]; then
  step "Starting local Postgres + Redis + Ollama via docker compose"
  command -v docker >/dev/null 2>&1 || fail "docker not found — install Docker Desktop or run without --with-docker"
  docker compose up -d postgres redis ollama
  DOCKER_USED=1
  ok "Docker services up"
fi

# ── Free ports if stuck ───────────────────────────────────
for port in 3001 5173; do
  if lsof -ti ":$port" >/dev/null 2>&1; then
    warn "Port $port already in use — attempting to free it"
    lsof -ti ":$port" | xargs -r kill -TERM 2>/dev/null || true
    sleep 1
  fi
done

# ── Start API + Web ───────────────────────────────────────
mkdir -p "$REPO_ROOT/.auditengine"
API_LOG="$REPO_ROOT/.auditengine/api.log"
WEB_LOG="$REPO_ROOT/.auditengine/web.log"
API_PID_FILE="$REPO_ROOT/.auditengine/api.pid"
WEB_PID_FILE="$REPO_ROOT/.auditengine/web.pid"

step "Starting Express API on :3001"
( cd "$REPO_ROOT" && nohup node server/index.js > "$API_LOG" 2>&1 & echo $! > "$API_PID_FILE" )
ok "API PID $(cat "$API_PID_FILE")"

step "Starting Vite dev server on :5173"
( cd "$REPO_ROOT" && nohup npm run dev > "$WEB_LOG" 2>&1 & echo $! > "$WEB_PID_FILE" )
ok "Web PID $(cat "$WEB_PID_FILE")"

# ── Trap shutdown ─────────────────────────────────────────
cleanup() {
  printf "\n${C_YEL}[!]${C_RST} Shutdown requested — stopping services\n"
  bash "$SCRIPT_DIR/stop.sh" || true
  exit 0
}
trap cleanup INT TERM

# ── Health polling ────────────────────────────────────────
step "Waiting for API health (max 15s)"
api_ok=0
for i in $(seq 1 30); do
  if curl -fsS http://localhost:3001/health >/dev/null 2>&1; then api_ok=1; break; fi
  sleep 0.5
done
if [ "$api_ok" = "1" ]; then ok "API healthy"; else
  warn "API not responding after 15s — recent log:"
  tail -n 20 "$API_LOG" || true
fi

step "Waiting for Vite (max 30s)"
web_ok=0
for i in $(seq 1 60); do
  if nc -z localhost 5173 >/dev/null 2>&1; then web_ok=1; break; fi
  sleep 0.5
done
if [ "$web_ok" = "1" ]; then ok "Vite ready"; else
  warn "Vite not responding after 30s — recent log:"
  tail -n 20 "$WEB_LOG" || true
fi

# ── Open browser ──────────────────────────────────────────
if [ "$NO_OPEN" = "0" ] && [ "$web_ok" = "1" ]; then
  open "http://localhost:5173" 2>/dev/null || true
fi

# ── Dashboard ─────────────────────────────────────────────
SUPABASE_HOST="$(keychain_get VITE_SUPABASE_URL | sed -E 's#https?://##; s#/##')"
ANTHROPIC_PRESENT="no"
[ -n "$(keychain_get ANTHROPIC_API_KEY)" ] && ANTHROPIC_PRESENT="yes"

printf "\n${C_BLU}══════════════════════════════════════════════════════════════${C_RST}\n"
printf "${C_GRN}  AuditEngine running locally${C_RST}\n"
printf "${C_BLU}══════════════════════════════════════════════════════════════${C_RST}\n"
printf "  Web         http://localhost:5173       %s\n" "$([ "$web_ok" = 1 ] && printf "${C_GRN}up${C_RST} (pid %s)" "$(cat "$WEB_PID_FILE")" || printf "${C_RED}down${C_RST}")"
printf "  API         http://localhost:3001       %s\n" "$([ "$api_ok" = 1 ] && printf "${C_GRN}up${C_RST} (pid %s)" "$(cat "$API_PID_FILE")" || printf "${C_RED}down${C_RST}")"
printf "  Supabase    %s\n" "${SUPABASE_HOST:-${C_DIM}not configured (localStorage fallback)${C_RST}}"
printf "  Anthropic   %s\n" "$([ "$ANTHROPIC_PRESENT" = yes ] && printf "${C_GRN}keyed${C_RST}" || printf "${C_DIM}not configured${C_RST}")"
[ "$DOCKER_USED" = "1" ] && printf "  Docker      postgres:5432  redis:6379  ollama:11434\n"
printf "  Logs        ${C_DIM}tail -f .auditengine/{api,web}.log${C_RST}\n"
printf "  Stop        ${C_DIM}./stop  or  Ctrl+C${C_RST}\n"
printf "${C_BLU}══════════════════════════════════════════════════════════════${C_RST}\n\n"

# ── Tail logs in foreground so Ctrl+C reaches us ──────────
printf "${C_DIM}Tailing logs — press Ctrl+C to stop everything${C_RST}\n"
tail -F "$API_LOG" "$WEB_LOG"
